name: Auto Push Changes

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto-update: $(date)" || echo "No changes to commit"
          git push 